export const DOCTOR_SPECIALIZATIONS = [
  'Cardiology',
  'Dermatology',
  'Neurology',
  'Pediatrics',
  'Psychiatry',
  'Orthopedics',
  'General Medicine',
  'Surgery',
  'Gastroenterology',
  'Pulmonology',
  'Nephrology',
  'Oncology',
  'Ophthalmology',
  'ENT',
  'Dentistry',
  'Gynecology',
  'Urology',
  'Anesthesiology',
  'Radiology',
  'Pathology',
];
